/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_kjudge_core_SolutionLauncher */

#ifndef _Included_ru_kjudge_core_SolutionLauncher
#define _Included_ru_kjudge_core_SolutionLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_kjudge_core_SolutionLauncher
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_kjudge_core_SolutionLauncher_init
  (JNIEnv *, jclass);

/*
 * Class:     ru_kjudge_core_SolutionLauncher
 * Method:    createTempDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_kjudge_core_SolutionLauncher_createTempDirectory
  (JNIEnv *, jobject);

/*
 * Class:     ru_kjudge_core_SolutionLauncher
 * Method:    deleteTemporaryDirectory
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_kjudge_core_SolutionLauncher_deleteTemporaryDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_kjudge_core_SolutionLauncher
 * Method:    checkSolution
 * Signature: (Lru/kjudge/core/CheckingLimits;Ljava/lang/String;Ljava/io/InputStream;Ljava/io/OutputStream;Ljava/io/Writer;)Lru/kjudge/core/CheckingResult;
 */
JNIEXPORT jobject JNICALL Java_ru_kjudge_core_SolutionLauncher_checkSolution
  (JNIEnv *, jobject, jobject, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
